### ISSUE TITLE
Missing signing

### ISSUE THREAD

**Issue by riderx** [akramhussein/Mute#16]
when adding your lib to a project in XCode 14 project won't build because of the lib don't have signed team

**Comment by undimon** [comment]
Confirm, plz fix

**Comment by akramhussein** [comment]
Will take a look

**Comment by riderx** [comment]
thanks 🙏

**Comment by riderx** [comment]
Seems adding 
```
s.pod_target_xcconfig = { 'CODE_SIGNING_ALLOWED' => 'NO' }
```
in https://github.com/akramhussein/Mute/blob/master/Mute.podspec 
fix the issue.
i do a PR

**Comment by akramhussein** [comment]
I've merged in #17 and believe it should resolve the issue. It is in the [0.6.1](https://github.com/akramhussein/Mute/releases/tag/0.6.1) release. 

This seems to be a bigger issue in many pods due to Xcode 14 and this may not be the correct fix for all, especially if you have more complicated projects. If that is the case, I suggest taking a look at implementing a fix in your projects `Podfile` using a `post_install` script as [explained here](https://stackoverflow.com/a/72600584). If using that approach, use `0.6.0` which does not have this change.

Thank you to @riderx for the PR #17
